all:  delay_and_handle_signals.c immediate_without_enter.c noecho.c
	gcc -g delay_and_handle_signals.c -o try-again-delay
	gcc -g immediate_without_enter.c -o try-again-immediate
	gcc -g noecho.c -o try-again-noecho
